Added target waypoint visualization
cs-24-sw-9-xx/MAEPS pull request #90
Opened 2024-11-11 13:23 UTC by S3JER

Functionality for target waypoints. 

TODO:  Connecting the functionality to the UI

2024-11-11 13:29 UTC, henneboy requested changes
Does this cause trouble for the work in progress by @Casper-NS or @miniJmo ?

2024-11-11 13:41 UTC, henneboy approved these changes

2024-11-12 08:13 UTC, mads256h commented
Rebase dis

2024-11-12 08:15 UTC, mads256h requested changes

2024-11-12 08:15 UTC, mads256h commented on Assets/Scripts/Map/Visualization/Patrolling/PatrollingHeatMapVisualizationMode.cs
> +namespace Maes.Assets.Scripts.Map.Visualization.Patrolling
Namespace is fucked up

2024-11-12 08:15 UTC, mads256h commented on Assets/Scripts/Map/Visualization/Patrolling/PatrollingTargetWaypointVisualizationMode.cs
> +namespace Maes.Assets.Scripts.Map.Visualization.Patrolling
Same here

2024-11-12 08:15 UTC, mads256h commented on Assets/Scripts/Map/Visualization/Patrolling/WaypointHeatMapVisualization.cs
> +namespace Maes.Assets.Scripts.Map.Visualization.Patrolling
And here

2024-11-12 09:30 UTC, mads256h requested changes

2024-11-12 09:30 UTC, mads256h commented on Assets/Scripts/UI/SimulationInfoUIControllers/PatrollingInfoUIController.cs
> +using Maes.Assets.Scripts.Map.Visualization.Patrolling;
Can you fix this namespace as well?

2024-11-12 11:08 UTC, mads256h approved these changes

2024-11-12 11:09 UTC, merged